# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-23 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0013_add_indexes_to_lcgm_date_for_and_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedailymetrics',
            name='todays_active_learners_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
