# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-23 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0012_auto_20200924_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedailymetrics',
            name='todays_active_learners_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
