# Generated by Django 2.2.16 on 2021-01-26 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0013_sitedailymetrics_todays_active_learners_count'),
        ('figures', '0015_add_enrollment_data_model'),
    ]

    operations = [
    ]
