# Generated by Django 2.2.16 on 2021-06-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0016_merge_20210126_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnercoursegrademetrics',
            name='total_progress_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='learnercoursegrademetrics',
            name='letter_grade',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
