# Generated by Django 2.2.16 on 2022-09-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0017_add_monthly_active_enrollment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedailymetrics',
            name='active_learners_this_month',
            field=models.IntegerField(default=0),
        ),
    ]
