# Generated by Django 4.2.19 on 2025-06-13 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0012_auto_20200924_0843'),
        ('figures', '0013_sitedailymetrics_todays_active_learners_count'),
        ('figures', '0018_coursedailymetrics_active_learners_this_month'),
    ]

    operations = [
    ]
