# Generated by Django 2.2.24 on 2025-05-05 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0018_coursedailymetrics_active_learners_this_month'),
        ('figures', '0016_add_collect_elapsed_to_ed_and_lcgm'),
    ]

    operations = [
    ]
